### ISSUE TITLE
Color and format log not working running IOS

### ISSUE THREAD

**Issue by dattd38** [Frezyx/talker#267]
Android Studio 2022.3.1 Patch 4
Device: Iphone 15 Pro Max
IOS: 17.5

![Google Chrome 2024-10-07 09 33 45](https://github.com/user-attachments/assets/737d00db-a21a-489e-9453-03a7ada39663)

**Comment by Aboneyx** [comment]
After updating vs code to version 1.94, the same thing happens to me. I don't think it's the package, most likely the debug adapter protocol or something related to it has been changed.

for now, you can temporarily disable it like this:
![image](https://github.com/user-attachments/assets/6a9e4a49-767d-47b4-8dbc-bc9e8632403e)

I also think to look at the issues with this package, since this package is used under the hood:
https://pub.dev/packages/ansicolor

**Comment by dattd38** [comment]
Do you have any way to get it working again? Help me

**Comment by dattd38** [comment]
> After updating vs code to version 1.94, the same thing happens to me. I don't think it's the package, most likely the debug adapter protocol or something related to it has been changed.
> 
> for now, you can temporarily disable it like this: ![image](https://private-user-images.githubusercontent.com/79087226/374009274-6a9e4a49-767d-47b4-8dbc-bc9e8632403e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNzQ2MzYsIm5iZiI6MTcyODI3NDMzNiwicGF0aCI6Ii83OTA4NzIyNi8zNzQwMDkyNzQtNmE5ZTRhNDktNzY3ZC00N2I0LThkYmMtYmM5ZTg2MzI0MDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA0MTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYTA0N2E2ZGU4MDZiNGEyMGNkZWE4NGIzZmNkZjE1ODFjMDlmN2E1NzBkMjkwMzUxMDdjYjk4OTVkM2JkZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P7Lc8pM8uOr2w-q1RQD9REX24StTbmUFiUhgI9Ujs5A)
> 
> I also think to look at the issues with this package, since this package is used under the hood: https://pub.dev/packages/ansicolor

Do you have any way to get it working again?

**Comment by Frezyx** [comment]
Hello everyone! 👋
This bug related to VScode issue https://github.com/microsoft/vscode/issues/230441

This problem was discovered in the new [September release](https://code.visualstudio.com/updates/v1_94) and covers a lot of programming languages and projects that using ANSI colors for console logs. 

VSCode team already make fix for [vscode-js-debug](https://github.com/microsoft/vscode-js-debug) and [promise](https://github.com/microsoft/vscode/issues/230441#issuecomment-2395235659) to make stable release with this fix next week

**Tmp Workaround**

In order to temporarily fix console logs you can disable logging with ANSI colors.
To make it you must set **enableColors** field to false like in example bellow

```dart
final talker = Talker(
    logger: TalkerLogger(
        settings: TalkerLoggerSettings(enableColors: false),
    ),
)
```

<img width="979" alt="image" src="https://github.com/user-attachments/assets/f4e4374f-4dd2-4f89-a12b-5169969af250">

**Comment by RinaZavr** [comment]
Pixel 5: API 34
VSCode: 1.94.0
Talker: 4.3.4
![image](https://github.com/user-attachments/assets/332f9cd1-fa5a-4674-90f0-e4aea15ea8df)
![image](https://github.com/user-attachments/assets/a2ab6a74-7a61-48b7-a8e5-d0ceb94101d9)
![image](https://github.com/user-attachments/assets/3a0dafe1-52d0-4e52-8cba-7067fb230a0e)

**Comment by Frezyx** [comment]
@RinaZavr to fix console logs you need to provide logger setting like in example 

```dart
    logger: TalkerLogger(
        settings: TalkerLoggerSettings(enableColors: false),
    ),
```

**Comment by Aboneyx** [comment]
> Hello everyone! 👋 This bug related to VScode issue [microsoft/vscode#230441](https://github.com/microsoft/vscode/issues/230441)
> 
> This problem was discovered in the new [September release](https://code.visualstudio.com/updates/v1_94) and covers a lot of programming languages and projects that using ANSI colors for console logs.
> 
> VSCode team already make fix for [vscode-js-debug](https://github.com/microsoft/vscode-js-debug) and [promise](https://github.com/microsoft/vscode/issues/230441#issuecomment-2395235659) to make stable release with this fix next week
> 
> **Tmp Workaround**
> 
> In order to temporarily fix console logs you can disable logging with ANSI colors. To make it you must set **enableColors** field to false like in example bellow
> 
> ```dart
> final talker = Talker(
>     logger: TalkerLogger(
>         settings: TalkerLoggerSettings(enableColors: false),
>     ),
> )
> ```
> 
> <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/40857927/374088189-f4e4374f-4dd2-4f89-a12b-5169969af250.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjAyNDQsIm5iZiI6MTcyODQ1OTk0NCwicGF0aCI6Ii80MDg1NzkyNy8zNzQwODgxODktZjRlNDM3NGYtNGRkMi00Zjg5LWExMmItNTE2OTk2OWFmMjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA3NDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMDIwNjM3OWFjNjYzNDViNDc4ZGEyYjhhMzJiNjkxMmFjMTdhYzQ2NzFmOTFlYmQ3MjkxNzhlZjkxNTEwMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XKQa87zC7xxJoNQcXjtYsk8V25A9zlYgroQf2ahP9ek">


A new version of VS code 1.94.1 has been released, where this bug has been fixed

**Comment by Frezyx** [comment]
@Aboneyx thank you for comment!
I have downloaded the new 1.94.1 version and logs are working as expected.

**Comment by dattd38** [comment]
> > Hello everyone! 👋 This bug related to VScode issue [microsoft/vscode#230441](https://github.com/microsoft/vscode/issues/230441)
> > This problem was discovered in the new [September release](https://code.visualstudio.com/updates/v1_94) and covers a lot of programming languages and projects that using ANSI colors for console logs.
> > VSCode team already make fix for [vscode-js-debug](https://github.com/microsoft/vscode-js-debug) and [promise](https://github.com/microsoft/vscode/issues/230441#issuecomment-2395235659) to make stable release with this fix next week
> > **Tmp Workaround**
> > In order to temporarily fix console logs you can disable logging with ANSI colors. To make it you must set **enableColors** field to false like in example bellow
> > ```dart
> > final talker = Talker(
> >     logger: TalkerLogger(
> >         settings: TalkerLoggerSettings(enableColors: false),
> >     ),
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/40857927/374088189-f4e4374f-4dd2-4f89-a12b-5169969af250.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjAyNDQsIm5iZiI6MTcyODQ1OTk0NCwicGF0aCI6Ii80MDg1NzkyNy8zNzQwODgxODktZjRlNDM3NGYtNGRkMi00Zjg5LWExMmItNTE2OTk2OWFmMjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA3NDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMDIwNjM3OWFjNjYzNDViNDc4ZGEyYjhhMzJiNjkxMmFjMTdhYzQ2NzFmOTFlYmQ3MjkxNzhlZjkxNTEwMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XKQa87zC7xxJoNQcXjtYsk8V25A9zlYgroQf2ahP9ek">
> 
> A new version of VS code 1.94.1 has been released, where this bug has been fixed

when i run on ios device or ios virtual machine it also does not log out color. i use mac os android studio

**Comment by weitsai** [comment]
Phone: iPhone 11 Pro
VSCode: 1.94.2
Talker Flutter: ^4.4.1
Talker Riverpod: 4.4.1

![截圖 2024-10-11 03 07 34](https://github.com/user-attachments/assets/c4a8aefb-d60d-4ed0-a67d-a0b48defb645)

**Comment by programmeraditya** [comment]
This still exists on Android Studio. I am using Mac, Android Studio Koala and iOS Simulator. 

```
final talker = Talker(
    logger: TalkerLogger(
        settings: TalkerLoggerSettings(enableColors: false),
    ),
)
```

Doing above doesn't resolve the issue either.
So far nothing has helped with iOS, but I can see the logs in color fine on Android.

**Comment by gaganyadav80** [comment]
I can also confirm still an issue with iOS Simulators on VSCode 1.99.2

**Comment by gaganyadav80** [comment]
I found a solution – define the `TalkerLogger.output` method as below. This is taken from the `TalkerFlutter.init()` implementation.

```dart
TalkerFlutter.init(
    formatter: const ColoredLoggerFormatter(),
    logger: TalkerLogger(
      output: (message) {
        if (kIsWeb) {
          // ignore: avoid_print
          print(message);
          return;
        }

        switch (defaultTargetPlatform) {
          case TargetPlatform.iOS:
          case TargetPlatform.macOS:
            log(message, name: 'Talker');
            break;
          default:
            debugPrint(message);
        }
      },
    ),
  )
```
